### ISSUE TITLE
postcss-load-options overwrites options in-place

### ISSUE THREAD

**Issue by Kovensky** [michael-ciniawsky/postcss-load-options#24]
## Problem

postcss-load-options overwrites the options object it receives
in-place, which causes a crash when the given object is actually memoized.

## Details

When postcss-load-options is invoked for processing a second file, node
throws an assertion as `require` is called with a non-string argument.

That specific problem may already be fixed by #18, but the presence of this
other bug also triggers it even if the user gives a string to be required.

## Error Logs

```
{ AssertionError: path must be a string
    at Module.require (module.js:497:3)
    at require (internal/module.js:20:19)
    at options (.../node_modules/postcss-load-options/lib/options.js:17:22)
    at .../node_modules/postcss-load-config/index.js:68:18
  name: 'AssertionError',
  actual: false,
  expected: true,
  operator: '==',
  message: 'path must be a string',
  generatedMessage: false }
```

## Issue [ Code ]

`postcss.config.js`:

```js
const memoize = require('memoizee')
const plugins = require('./postcss.plugins.js')

const config = memoize((production, parser) => {
  return Object.assign({
    plugins: plugins(production, parser)
  }, parser != null ? { parser } : {})
}, { primitive: true, length: false })

// const sugarss = require('sugarss')

module.exports = function postcssConfig (ctx) {
  return config(
    ctx.env === 'production',
    // 'sugarss' until https://github.com/michael-ciniawsky/postcss-load-options/pull/18 is released
    ctx.webpack.resourcePath.endsWith('.sss') ? 'sugarss' : null
  )
}
```

`config`, when called, will return the same object for the same arguments, so modifying the object in postcss-load-options contaminates the memoization cache, replacing `options.parser` with the result of `require(options.parser)`, which breaks the workaround :)

I can work around it by returning a new copy of the object every time, but adding workarounds to make workarounds work is not optimal.

**Comment by michael-ciniawsky** [comment]
@Kovensky hmm... where to start 😛 

- Can you explain in which context you want to use the code posted above?
- Would it be possible to memoize within `postcss-load-*` ? 
- How much speedup benefits can be approximately expected by this optimization?
- If someone calls `postcss-load-*` with `ctx` e.g

```js
const ctx = { foo: 'bar' }

postcssrc(ctx).then(( {options, plugins, file} ) => {...})
```
  the memoization cache would be always contaminated 🤔 ?

> // 'sugarss' until https://github.com/michael-ciniawsky/postcss-load-options/pull/18 is released

Yep I'm on it right know, sry for the delay

Since we talking about 'advanced' usage anyways, would you mind taking a look at [postcss-loader #66](https://github.com/postcss/postcss-loader/issues/66) ? It's about hot reloading the config on changes (vars, colors, urls, etc...), but I'm not sure, if the pseudo code of mine towards the end of this thread would be working.

**Comment by michael-ciniawsky** [comment]
@Kovensky Can we do something about within `postcss-load-options` ? 😛
